### ISSUE TITLE
undefined method `closed?'

### ISSUE THREAD

**Issue by leckylao** [ngauthier/tubesock#34]
tubesock-0.2.4/lib/tubesock.rb:72:in `close': undefined method `closed?' for #<Puma::MiniSSL::Socket:0x00000005b11d90> (NoMethodError)

When using with puma ssl. The socket class becomes Puma::MiniSSL::Socket and it caused this error.

**Comment by rickychilcott** [comment]
Looks like this issue can be closed based on #35 being merged. Correct?

**Comment by leckylao** [comment]
👍
