### ISSUE TITLE
Failing plain rack application

### ISSUE THREAD

**Issue by vmoravec** [ngauthier/tubesock#45]
Hi, 
I tried to run the example in the README from within a `config.ru` without any additions, and it fails with `Rack::Lint::LintError: Status must be >=100 seen as integer` when querying it from within a Firebug with:
```javascript
// backend is powered by puma
var socket = new WebSocket("ws://localhost:9292")
var socket.send("Hello")
```
Whatever I have tried, I always failed with different errors. What I'm doing wrong, please? I am going to use `tubesock`  inside a Sinatra app, but had no success with any possible configuration even from a plain `rack` sofar.
Thanks for any hints and help.

**Comment by ngauthier** [comment]
Thanks for the report. We're tracking this in #32. This is a known issue with newer versions of rack.
